global:
  scrape_interval:     10s
  evaluation_interval: 10s
  external_labels:
      monitor: 'node'
scrape_configs:
  - job_name: 'Prometheus'
    static_configs:
      - targets: ['172.28.128.70:9090','172.28.128.71:9090']
  - job_name: 'Node-exporter'
    static_configs:
      - targets: ['172.28.128.70:9100','172.28.128.71:9100']
